### ISSUE TITLE
NotImplementedError: Only 3D, 4D, 5D padding with non-constant padding are supported for now

### ISSUE THREAD

**Issue by wj-gxy** [sanjitdp/audio-generation-wavegan#1]
NotImplementedError: Only 3D, 4D, 5D padding with non-constant padding are supported for now in class PhaseShuffle(nn.Module):

Do you know why? And can you help me to solve this problem?

**Comment by sanjitdp** [comment]
Hey! You can see section 3.3 of (https://arxiv.org/pdf/1802.04208.pdf) for the description of the `PhaseShuffle` algorithm; the `PhaseShuffle(nn.Module)` class is currently only meant to work with 2D tensors. The issue might be that you're trying to use the code for multi-channel or stereo audio, which isn't currently supported. Unfortunately this is an older project and I likely won't be updating it to work with other audio formats, but maybe try using a mono audio file.
